apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: viken-no-fint-flyt-elements-dispatch-gateway
spec:
  itemPath: "vaults/aks-alpha-vault/items/viken-no-fint-flyt-elements-dispatch-gateway"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-elements-dispatch-gateway
  name: fint-flyt-elements-dispatch-gateway
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-elements-dispatch-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-elements-dispatch-gateway
  name: fint-flyt-elements-dispatch-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-elements-dispatch-gateway
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-elements-dispatch-gateway
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-elements-dispatch-gateway:dummy
          name: fint-flyt-elements-dispatch-gateway
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
            - secretRef:
                name: viken-no-fint-flyt-elements-dispatch-gateway
            - secretRef:
                name: oauth2-client-flyt-file-service
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc' }
            - { name: fint.org-id, value: 'viken.no' }
            - { name: fint.client.base-url, value: 'https://beta.felleskomponent.no' }
            - { name: fint.flyt.base-url, value: 'https://viken-no-skjema.vigoiks.no' }
            - { name: fint.dispatch-gateway.authorization.enable, value: "true" }
            - { name: logging.level.reactor.netty.http.client, value: 'debug' }