fint:
  application-id: fint-flyt-elements-dispatch-gateway
server:
  max-http-header-size: 40KB
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - fint-client
      - flyt-file-client