apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-flyt-archive-dispatch-gateway
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/fintlabs/fint-flyt-archive-dispatch-gateway:sha-0000000
          envFrom:
            - secretRef:
                name: vlfk-no-fint-flyt-archive-dispatch-gateway